readings = {
    "Today": {"Name": "Today's Energy",
              "Meaning": ["Main Energy for Today"]},
    "Path": {"Name": "Two Paths",
             "Meaning": ["First Path", "Second Path"]},
    "Past": {"Name": "Past, Present, Future",
             "Meaning": ["Past", "Present", "Future"]},
    "Advice": {"Name": "Situation, Obstacle, Advice",
               "Meaning": ["Situation", "Obstacle", "Advice"]},
    "Compass": {"Name": "Compass Spread",
                "Meaning": ["South", "West", "East", "North"]},
    "Love": {"Name": "Love Spread",
             "Meaning": ["Own Thoughts", "Own Words", "Own Feelings",
                         "Partner Thoughts", "Partner Words", "Partner Feelings"]},
    "Celtic": {"Name": "Celtic Cross",
               "Meaning": ["Situation", "Challenge", "Focus",
                           "Recent Past", "Possibilities", "Near Future",
                           "Power", "Environment", "Hopes", "Outcome"]},
    "General": {"Name": "General Spread",
                "Meaning": ["Present", "Strength", "Weakness / Hidden Influences",
                            "Air / Communication / Mental / Thoughts",
                            "Fire / Passion / Creativity / Active",
                            "Earth / Realistic / Physical Aspects / Practical",
                            "Water / Emotions / Relationships / Sensitivity",
                            "Past", "Future 1 Month"]},
    "Needs": {"Name": "Hierarchy of Needs",
              "Meaning": ["Physiological", "Safety", "Love and Belonging",
                          "Esteem", "Self-Actualization"]},
    "Dream": {"Name": "Dream Messages",
              "Meaning": ["Past Event", "Dream Theme", "Waking Life Block",
                          "Message", "Lesson"]},
    "Life": {"Name": "Your Life Right Now",
             "Meaning": ["Present Self", "Resources / Money Matters", "Mental / Internal Communication",
                         "Home / Family", "Creativity / Progeny", "Job / Occupation / Physical Health",
                         "Love / Romance", "Changes to Come", "Knowledge / Spirituality", "Career / Ambitions",
                         "Community / Allies", "Challenges / Losses"]},
}


tarot_deck = [
    # Major Arcana
    "The Fool",
    "The Magician",
    "The High Priestess",
    "The Empress",
    "The Emperor",
    "The Hierophant",
    "The Lovers",
    "The Chariot",
    "Strength",
    "The Hermit",
    "Wheel of Fortune",
    "Justice",
    "The Hanged Man",
    "Death",
    "Temperance",
    "The Devil",
    "The Tower",
    "The Star",
    "The Moon",
    "The Sun",
    "Judgement",
    "The World",

    # Wands
    "Ace of Wands",
    "Two of Wands",
    "Three of Wands",
    "Four of Wands",
    "Five of Wands",
    "Six of Wands",
    "Seven of Wands",
    "Eight of Wands",
    "Nine of Wands",
    "Ten of Wands",
    "Page of Wands",
    "Knight of Wands",
    "Queen of Wands",
    "King of Wands",

    # Cups
    "Ace of Cups",
    "Two of Cups",
    "Three of Cups",
    "Four of Cups",
    "Five of Cups",
    "Six of Cups",
    "Seven of Cups",
    "Eight of Cups",
    "Nine of Cups",
    "Ten of Cups",
    "Page of Cups",
    "Knight of Cups",
    "Queen of Cups",
    "King of Cups",

    # Swords
    "Ace of Swords",
    "Two of Swords",
    "Three of Swords",
    "Four of Swords",
    "Five of Swords",
    "Six of Swords",
    "Seven of Swords",
    "Eight of Swords",
    "Nine of Swords",
    "Ten of Swords",
    "Page of Swords",
    "Knight of Swords",
    "Queen of Swords",
    "King of Swords",

    # Pentacles
    "Ace of Pentacles",
    "Two of Pentacles",
    "Three of Pentacles",
    "Four of Pentacles",
    "Five of Pentacles",
    "Six of Pentacles",
    "Seven of Pentacles",
    "Eight of Pentacles",
    "Nine of Pentacles",
    "Ten of Pentacles",
    "Page of Pentacles",
    "Knight of Pentacles",
    "Queen of Pentacles",
    "King of Pentacles",
]
